//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CventRegManager.MRACventAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MRARegForISSoap", Namespace="http://tempuri.org/")]
    public partial class MRARegForIS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRegistrantsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegistrationDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MRARegForIS() {
            this.Url = global::CventRegManager.Properties.Settings.Default.CventRegManager_MRACventAPI_MRARegForIS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRegistrantsCompletedEventHandler GetRegistrantsCompleted;
        
        /// <remarks/>
        public event GetRegistrationDetailsCompletedEventHandler GetRegistrationDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegistrants", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public registrantList[] GetRegistrants(string EventId, string APIEventPW) {
            object[] results = this.Invoke("GetRegistrants", new object[] {
                        EventId,
                        APIEventPW});
            return ((registrantList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegistrantsAsync(string EventId, string APIEventPW) {
            this.GetRegistrantsAsync(EventId, APIEventPW, null);
        }
        
        /// <remarks/>
        public void GetRegistrantsAsync(string EventId, string APIEventPW, object userState) {
            if ((this.GetRegistrantsOperationCompleted == null)) {
                this.GetRegistrantsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegistrantsOperationCompleted);
            }
            this.InvokeAsync("GetRegistrants", new object[] {
                        EventId,
                        APIEventPW}, this.GetRegistrantsOperationCompleted, userState);
        }
        
        private void OnGetRegistrantsOperationCompleted(object arg) {
            if ((this.GetRegistrantsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegistrantsCompleted(this, new GetRegistrantsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegistrationDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DetailedRegistrant[] GetRegistrationDetails(string EventId, string APIEventPW, string MRARegistrationId) {
            object[] results = this.Invoke("GetRegistrationDetails", new object[] {
                        EventId,
                        APIEventPW,
                        MRARegistrationId});
            return ((DetailedRegistrant[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegistrationDetailsAsync(string EventId, string APIEventPW, string MRARegistrationId) {
            this.GetRegistrationDetailsAsync(EventId, APIEventPW, MRARegistrationId, null);
        }
        
        /// <remarks/>
        public void GetRegistrationDetailsAsync(string EventId, string APIEventPW, string MRARegistrationId, object userState) {
            if ((this.GetRegistrationDetailsOperationCompleted == null)) {
                this.GetRegistrationDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegistrationDetailsOperationCompleted);
            }
            this.InvokeAsync("GetRegistrationDetails", new object[] {
                        EventId,
                        APIEventPW,
                        MRARegistrationId}, this.GetRegistrationDetailsOperationCompleted, userState);
        }
        
        private void OnGetRegistrationDetailsOperationCompleted(object arg) {
            if ((this.GetRegistrationDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegistrationDetailsCompleted(this, new GetRegistrationDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class registrantList {
        
        private string mRARegistrationIdParentField;
        
        private string mRARegConfirmationField;
        
        private string contactIdField;
        
        private string organizationIdField;
        
        private string emailField;
        
        private System.DateTime registrationDateField;
        
        private System.DateTime mRAModifiedDateTimeField;
        
        private System.DateTime lastModifiedFinancialDateTimeField;
        
        private string cancellationDateField;
        
        private string statusField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string organizationNameField;
        
        private string titleField;
        
        private string registrationTypeField;
        
        /// <remarks/>
        public string MRARegistrationIdParent {
            get {
                return this.mRARegistrationIdParentField;
            }
            set {
                this.mRARegistrationIdParentField = value;
            }
        }
        
        /// <remarks/>
        public string MRARegConfirmation {
            get {
                return this.mRARegConfirmationField;
            }
            set {
                this.mRARegConfirmationField = value;
            }
        }
        
        /// <remarks/>
        public string ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MRAModifiedDateTime {
            get {
                return this.mRAModifiedDateTimeField;
            }
            set {
                this.mRAModifiedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastModifiedFinancialDateTime {
            get {
                return this.lastModifiedFinancialDateTimeField;
            }
            set {
                this.lastModifiedFinancialDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CancellationDate {
            get {
                return this.cancellationDateField;
            }
            set {
                this.cancellationDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationType {
            get {
                return this.registrationTypeField;
            }
            set {
                this.registrationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GuestRegistration {
        
        private string guestIdField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string emailAddressField;
        
        private string confirmationNumberField;
        
        private string registrationTypeField;
        
        /// <remarks/>
        public string GuestId {
            get {
                return this.guestIdField;
            }
            set {
                this.guestIdField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmationNumber {
            get {
                return this.confirmationNumberField;
            }
            set {
                this.confirmationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationType {
            get {
                return this.registrationTypeField;
            }
            set {
                this.registrationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomQuestion {
        
        private string mRAIdField;
        
        private string questionCodeField;
        
        private string questionNameField;
        
        private string answerField;
        
        private string[] answersField;
        
        /// <remarks/>
        public string MRAId {
            get {
                return this.mRAIdField;
            }
            set {
                this.mRAIdField = value;
            }
        }
        
        /// <remarks/>
        public string QuestionCode {
            get {
                return this.questionCodeField;
            }
            set {
                this.questionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string QuestionName {
            get {
                return this.questionNameField;
            }
            set {
                this.questionNameField = value;
            }
        }
        
        /// <remarks/>
        public string Answer {
            get {
                return this.answerField;
            }
            set {
                this.answerField = value;
            }
        }
        
        /// <remarks/>
        public string[] Answers {
            get {
                return this.answersField;
            }
            set {
                this.answersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OptionalItem {
        
        private string mRAIdField;
        
        private System.DateTime optinalItemRegDateField;
        
        private string optionalItemCodeField;
        
        private string sessionIdField;
        
        private int quantityField;
        
        private decimal optionalFeeField;
        
        private string optionalItemNameField;
        
        private string actionField;
        
        /// <remarks/>
        public string MRAId {
            get {
                return this.mRAIdField;
            }
            set {
                this.mRAIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OptinalItemRegDate {
            get {
                return this.optinalItemRegDateField;
            }
            set {
                this.optinalItemRegDateField = value;
            }
        }
        
        /// <remarks/>
        public string OptionalItemCode {
            get {
                return this.optionalItemCodeField;
            }
            set {
                this.optionalItemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal OptionalFee {
            get {
                return this.optionalFeeField;
            }
            set {
                this.optionalFeeField = value;
            }
        }
        
        /// <remarks/>
        public string OptionalItemName {
            get {
                return this.optionalItemNameField;
            }
            set {
                this.optionalItemNameField = value;
            }
        }
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegCode {
        
        private string mRAIdField;
        
        private string discountNameField;
        
        private string regCodeValueField;
        
        private string discountTypeField;
        
        private decimal discountAmountField;
        
        /// <remarks/>
        public string MRAId {
            get {
                return this.mRAIdField;
            }
            set {
                this.mRAIdField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountName {
            get {
                return this.discountNameField;
            }
            set {
                this.discountNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegCodeValue {
            get {
                return this.regCodeValueField;
            }
            set {
                this.regCodeValueField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountType {
            get {
                return this.discountTypeField;
            }
            set {
                this.discountTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal DiscountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transaction {
        
        private string mRAIdField;
        
        private string transactionTypeField;
        
        private System.DateTime transactionDateField;
        
        private decimal transactionAmountField;
        
        /// <remarks/>
        public string MRAId {
            get {
                return this.mRAIdField;
            }
            set {
                this.mRAIdField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal TransactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetailedRegistrant {
        
        private string mRARegistrationIdParentField;
        
        private string mRARegConfirmationField;
        
        private string statusField;
        
        private System.DateTime registrationDateField;
        
        private string cancellationDateField;
        
        private string registrationTypeField;
        
        private string registrationItemField;
        
        private string registrationItemCodeField;
        
        private decimal registrationItemFeeField;
        
        private decimal registrationTotalFeeField;
        
        private string contactIdField;
        
        private string organizationIdField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string salutationField;
        
        private string badgeNameField;
        
        private string titleField;
        
        private string roleField;
        
        private string jobFunctionField;
        
        private string workPhoneField;
        
        private string faxField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateProvinceField;
        
        private string zipField;
        
        private string countryField;
        
        private string mobilePhoneField;
        
        private string genderField;
        
        private string ethnicityField;
        
        private string cancel_Substitute_NotesField;
        
        private bool usingAPartnerCodeField;
        
        private string affiliatedWithField;
        
        private bool scholarshipSponsorField;
        
        private string fundedByField;
        
        private string lengthOfTimeField;
        
        private string birthYearField;
        
        private string assistantEmailField;
        
        private string facebookURLField;
        
        private string twitterField;
        
        private string blogField;
        
        private string linkedInField;
        
        private string organizationNameField;
        
        private string organizationTypeField;
        
        private bool orgWorkInternationallyField;
        
        private string organizationWebsiteField;
        
        private string iSIndividualInterestCategoriesField;
        
        private bool specialNeedsYesNoField;
        
        private string specialNeedsTextField;
        
        private bool firstTimeAtConferenceField;
        
        private string greatestInfluenceToRegisterField;
        
        private string greatestInfluenceTextField;
        
        private bool includeInRosterField;
        
        private bool optOutPromoMaterialField;
        
        private string speakingAtField;
        
        private string[] interestCategoriesField;
        
        private string[] iS_InterestCategoriesField;
        
        private string[] dietaryNeedsField;
        
        private Transaction[] transactionsField;
        
        private RegCode[] registrationCodesField;
        
        private OptionalItem[] optionalItemRegistrationsField;
        
        private CustomQuestion[] customQuestionsField;
        
        private GuestRegistration[] guestRegistrationsField;
        
        /// <remarks/>
        public string MRARegistrationIdParent {
            get {
                return this.mRARegistrationIdParentField;
            }
            set {
                this.mRARegistrationIdParentField = value;
            }
        }
        
        /// <remarks/>
        public string MRARegConfirmation {
            get {
                return this.mRARegConfirmationField;
            }
            set {
                this.mRARegConfirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        public string CancellationDate {
            get {
                return this.cancellationDateField;
            }
            set {
                this.cancellationDateField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationType {
            get {
                return this.registrationTypeField;
            }
            set {
                this.registrationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationItem {
            get {
                return this.registrationItemField;
            }
            set {
                this.registrationItemField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationItemCode {
            get {
                return this.registrationItemCodeField;
            }
            set {
                this.registrationItemCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal RegistrationItemFee {
            get {
                return this.registrationItemFeeField;
            }
            set {
                this.registrationItemFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal RegistrationTotalFee {
            get {
                return this.registrationTotalFeeField;
            }
            set {
                this.registrationTotalFeeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string BadgeName {
            get {
                return this.badgeNameField;
            }
            set {
                this.badgeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public string JobFunction {
            get {
                return this.jobFunctionField;
            }
            set {
                this.jobFunctionField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Ethnicity {
            get {
                return this.ethnicityField;
            }
            set {
                this.ethnicityField = value;
            }
        }
        
        /// <remarks/>
        public string Cancel_Substitute_Notes {
            get {
                return this.cancel_Substitute_NotesField;
            }
            set {
                this.cancel_Substitute_NotesField = value;
            }
        }
        
        /// <remarks/>
        public bool UsingAPartnerCode {
            get {
                return this.usingAPartnerCodeField;
            }
            set {
                this.usingAPartnerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AffiliatedWith {
            get {
                return this.affiliatedWithField;
            }
            set {
                this.affiliatedWithField = value;
            }
        }
        
        /// <remarks/>
        public bool ScholarshipSponsor {
            get {
                return this.scholarshipSponsorField;
            }
            set {
                this.scholarshipSponsorField = value;
            }
        }
        
        /// <remarks/>
        public string FundedBy {
            get {
                return this.fundedByField;
            }
            set {
                this.fundedByField = value;
            }
        }
        
        /// <remarks/>
        public string LengthOfTime {
            get {
                return this.lengthOfTimeField;
            }
            set {
                this.lengthOfTimeField = value;
            }
        }
        
        /// <remarks/>
        public string BirthYear {
            get {
                return this.birthYearField;
            }
            set {
                this.birthYearField = value;
            }
        }
        
        /// <remarks/>
        public string AssistantEmail {
            get {
                return this.assistantEmailField;
            }
            set {
                this.assistantEmailField = value;
            }
        }
        
        /// <remarks/>
        public string FacebookURL {
            get {
                return this.facebookURLField;
            }
            set {
                this.facebookURLField = value;
            }
        }
        
        /// <remarks/>
        public string Twitter {
            get {
                return this.twitterField;
            }
            set {
                this.twitterField = value;
            }
        }
        
        /// <remarks/>
        public string Blog {
            get {
                return this.blogField;
            }
            set {
                this.blogField = value;
            }
        }
        
        /// <remarks/>
        public string LinkedIn {
            get {
                return this.linkedInField;
            }
            set {
                this.linkedInField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationType {
            get {
                return this.organizationTypeField;
            }
            set {
                this.organizationTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool OrgWorkInternationally {
            get {
                return this.orgWorkInternationallyField;
            }
            set {
                this.orgWorkInternationallyField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationWebsite {
            get {
                return this.organizationWebsiteField;
            }
            set {
                this.organizationWebsiteField = value;
            }
        }
        
        /// <remarks/>
        public string ISIndividualInterestCategories {
            get {
                return this.iSIndividualInterestCategoriesField;
            }
            set {
                this.iSIndividualInterestCategoriesField = value;
            }
        }
        
        /// <remarks/>
        public bool SpecialNeedsYesNo {
            get {
                return this.specialNeedsYesNoField;
            }
            set {
                this.specialNeedsYesNoField = value;
            }
        }
        
        /// <remarks/>
        public string SpecialNeedsText {
            get {
                return this.specialNeedsTextField;
            }
            set {
                this.specialNeedsTextField = value;
            }
        }
        
        /// <remarks/>
        public bool FirstTimeAtConference {
            get {
                return this.firstTimeAtConferenceField;
            }
            set {
                this.firstTimeAtConferenceField = value;
            }
        }
        
        /// <remarks/>
        public string GreatestInfluenceToRegister {
            get {
                return this.greatestInfluenceToRegisterField;
            }
            set {
                this.greatestInfluenceToRegisterField = value;
            }
        }
        
        /// <remarks/>
        public string GreatestInfluenceText {
            get {
                return this.greatestInfluenceTextField;
            }
            set {
                this.greatestInfluenceTextField = value;
            }
        }
        
        /// <remarks/>
        public bool IncludeInRoster {
            get {
                return this.includeInRosterField;
            }
            set {
                this.includeInRosterField = value;
            }
        }
        
        /// <remarks/>
        public bool OptOutPromoMaterial {
            get {
                return this.optOutPromoMaterialField;
            }
            set {
                this.optOutPromoMaterialField = value;
            }
        }
        
        /// <remarks/>
        public string SpeakingAt {
            get {
                return this.speakingAtField;
            }
            set {
                this.speakingAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("interestCategory")]
        public string[] InterestCategories {
            get {
                return this.interestCategoriesField;
            }
            set {
                this.interestCategoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("IS_interestCategory")]
        public string[] IS_InterestCategories {
            get {
                return this.iS_InterestCategoriesField;
            }
            set {
                this.iS_InterestCategoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DietaryNeed")]
        public string[] DietaryNeeds {
            get {
                return this.dietaryNeedsField;
            }
            set {
                this.dietaryNeedsField = value;
            }
        }
        
        /// <remarks/>
        public Transaction[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
            }
        }
        
        /// <remarks/>
        public RegCode[] RegistrationCodes {
            get {
                return this.registrationCodesField;
            }
            set {
                this.registrationCodesField = value;
            }
        }
        
        /// <remarks/>
        public OptionalItem[] OptionalItemRegistrations {
            get {
                return this.optionalItemRegistrationsField;
            }
            set {
                this.optionalItemRegistrationsField = value;
            }
        }
        
        /// <remarks/>
        public CustomQuestion[] CustomQuestions {
            get {
                return this.customQuestionsField;
            }
            set {
                this.customQuestionsField = value;
            }
        }
        
        /// <remarks/>
        public GuestRegistration[] GuestRegistrations {
            get {
                return this.guestRegistrationsField;
            }
            set {
                this.guestRegistrationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRegistrantsCompletedEventHandler(object sender, GetRegistrantsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegistrantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegistrantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public registrantList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((registrantList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRegistrationDetailsCompletedEventHandler(object sender, GetRegistrationDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegistrationDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegistrationDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DetailedRegistrant[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DetailedRegistrant[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591